### ISSUE TITLE
No build target [Octane]

### ISSUE THREAD

**Issue by jrock2004** [embermap/ember-cli-tailwind#191]
Just generated a new Octane project and when I try to install tailwind-css I am getting errors. When I try to start server I get `WARNING: No build target was detected for ember-cli-tailwind. Tailwind is not being included in your project.`.

From install log

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: MODULE_NOT_FOUND
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'broccoli-rollup'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'broccoli-rollup'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'broccoli-rollup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/john.costanzo/Development/online-booking/node_modules/ember-cli-tailwind/lib/build-tailwind.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by jrock2004** [comment]
Just going to use other method of tailwind since other issue states you probably should
