### ISSUE TITLE
addon/utils/classes-for-module-style.js: No ESLint configuration found.

### ISSUE THREAD

**Issue by gossi** [embermap/ember-cli-tailwind#95]
I've tried latest ember-cli + source addon (using ember-octane-addon-blueprint) and installed `ec-addon-docs`. When trying to serve it. I come across this error message:

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:342:29)
    at CLIEngine.getConfigForFile (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/cli-engine.js:729:29)
    at EslintValidationFilter.cacheKeyProcessString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/lib/index.js:118:26)
    at Object.processString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:30:19)
    at Processor.processString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/index.js:336:16)
    at initializePromise (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:520:5)
  - code: [undefined]
  - codeFrame: No ESLint configuration found.
  - errorMessage: addon/utils/classes-for-module-style.js: No ESLint configuration found.
        in /var/folders/tv/67gb0k1s7yz4f0cgn8kvqbj00000gn/T/broccoli-45803KLZj2hsEGDqm/out-391-funnel
        at broccoli-persistent-filter:EslintValidationFilter
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: addon/utils/classes-for-module-style.js
    - line: [undefined]
    - treeDir: /var/folders/tv/67gb0k1s7yz4f0cgn8kvqbj00000gn/T/broccoli-45803KLZj2hsEGDqm/out-391-funnel
  - message: addon/utils/classes-for-module-style.js: No ESLint configuration found.
        in /var/folders/tv/67gb0k1s7yz4f0cgn8kvqbj00000gn/T/broccoli-45803KLZj2hsEGDqm/out-391-funnel
        at broccoli-persistent-filter:EslintValidationFilter
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:EslintValidationFilter
  - originalErrorMessage: No ESLint configuration found.
  - stack: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/config.js:342:29)
    at CLIEngine.getConfigForFile (/Users/thomas/code/packages/my-project/node_modules/eslint/lib/cli-engine.js:729:29)
    at EslintValidationFilter.cacheKeyProcessString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/lib/index.js:118:26)
    at Object.processString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:30:19)
    at Processor.processString (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/index.js:336:16)
    at initializePromise (/Users/thomas/code/packages/my-project/packages/ember-my-project/node_modules/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:520:5)
```

I don't know if this really is related to `ember-cli-tailwind` - it just happens to be my last trace, so you might close it right away.

Here is my `package.json`:

```
{
  "name": "my-project",
  "version": "0.0.0",
  "keywords": [
    "ember-addon"
  ],
  "private": true,
  "description": "Small description for my-project goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test",
    "prepublishOnly": "ember ts:precompile",
    "postpublish": "ember ts:clean"
  },
  "dependencies": {
    "ember-auto-import": "^1.2.20",
    "ember-cli-babel": "^7.4.3",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-typescript": "^2.0.0-rc.2",
    "ember-css-modules": "npm:@buschtoens/ember-css-modules@1.2.0-beta.2"
  },
  "devDependencies": {
    "@ember-decorators/babel-transforms": "^5.1.3",
    "@ember/optional-features": "^0.7.0",
    "@glimmer/component": "^0.14.0-alpha.3",
    "@types/ember": "^3.0.27",
    "@types/ember-qunit": "^3.4.5",
    "@types/ember-test-helpers": "^1.0.4",
    "@types/ember-testing-helpers": "^0.0.3",
    "@types/ember__test-helpers": "^0.7.7",
    "@types/qunit": "^2.5.4",
    "@types/rsvp": "^4.0.2",
    "babel-eslint": "^8.0.2",
    "broccoli-asset-rev": "^3.0.0",
    "ember-cli": "ember-cli/ember-cli#1fee05d354b3a231409062ef83256a53a049e1e4",
    "ember-cli-addon-docs": "buschtoens/ember-cli-addon-docs#fix/module-unification",
    "ember-cli-addon-docs-esdoc": "buschtoens/ember-cli-addon-docs-esdoc#feat/typescript",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-git": "^1.3.3",
    "ember-cli-deploy-git-ci": "^1.0.1",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^2.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-typescript-blueprints": "^2.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.4.0",
    "ember-resolver": "^5.1.2",
    "ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/dcebf841eb2a44d3d3522e4533ad4da9994a5365.tgz",
    "eslint-plugin-ember": "^6.2.0",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.4",
    "typescript": "^3.3.3"
  },
  "engines": {
    "node": "6.* || 8.* || >= 10.*"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by gossi** [comment]
The conversation on discord that solved it:

<img width="742" alt="bildschirmfoto 2019-03-03 um 12 37 09" src="https://user-images.githubusercontent.com/283700/53694581-2de50400-3db1-11e9-9438-6d64b0533b08.png">

I can happily close this 😃

**Comment by samselikoff** [comment]
Awesome!

Anything needed on our end?

**Comment by gossi** [comment]
Nope. But in case people come here and run into the same problem, all they need to do is probably get rid of `ember-cli-eslint` dependency and they are good to go 😃
